const C={
ru:{nav:["О нас","Баскетбол","Филиал","Контакты"],eyebrow:"SHARK TEAM • ДЕТСКИЙ БАСКЕТБОЛ • ТАШКЕНТ",title:"РАСТИ. ИГРАЙ.\nСТАНОВИСЬ СИЛЬНЕЕ.",lead:"Баскетбольные тренировки для детей 8–16 лет. Команда, дисциплина, движение и уверенность — в одном зале.",cta:"Записаться на пробное",price:"50 000 сум",sport:"БАСКЕТБОЛ",sportText:"Тренировки в действующей группе под руководством тренера Дилшода.",age:"8–16 лет",ageLabel:"Возраст",days:"ВТ • ЧТ • СБ",daysLabel:"Дни",time:"17:00",timeLabel:"Начало",coach:"Дилшод",coachLabel:"Тренер",branch:"ШАХРИСТАН",school:"Школа №117",place:"рядом с метро Шахристан",route:"Построить маршрут",trial:"ПРОБНОЕ ЗАНЯТИЕ",trialText:"Познакомьтесь с тренером, группой и форматом тренировок.",about:"БОЛЬШЕ, ЧЕМ ПРОСТО ТРЕНИРОВКА.",aboutText:"SHARK TEAM создаёт спортивную среду, где ребёнок тренируется в команде, развивается физически и привыкает к дисциплине.",footer:"Детский спорт в Ташкенте"},
uz:{nav:["Biz haqimizda","Basketbol","Filial","Aloqa"],eyebrow:"SHARK TEAM • BOLALAR BASKETBOLI • TOSHKENT",title:"O‘S. O‘YNA.\nKUCHLIROQ BO‘L.",lead:"8–16 yoshli bolalar uchun basketbol mashg‘ulotlari. Jamoa, intizom, harakat va ishonch — bir zalda.",cta:"Sinov mashg‘ulotiga yozilish",price:"50 000 so‘m",sport:"BASKETBOL",sportText:"Murabbiy Dilshod boshchiligidagi amaldagi guruhda mashg‘ulotlar.",age:"8–16 yosh",ageLabel:"Yosh",days:"SESH • PAY • SHAN",daysLabel:"Kunlar",time:"17:00",timeLabel:"Boshlanishi",coach:"Dilshod",coachLabel:"Murabbiy",branch:"SHAHRISTON",school:"117-maktab",place:"Shahriston metrosi yaqinida",route:"Yo‘nalishni ochish",trial:"SINOV MASHG‘ULOTI",trialText:"Murabbiy, guruh va mashg‘ulot formati bilan tanishing.",about:"ODDIY MASHG‘ULOTDAN KO‘PROQ.",aboutText:"SHARK TEAM bolalar jamoada shug‘ullanadigan, jismonan rivojlanadigan va intizomga o‘rganadigan sport muhitini yaratadi.",footer:"Toshkentdagi bolalar sporti"}} as const;
export default function Home({params}:{params:{locale:string}}){const l=params.locale==="uz"?"uz":"ru",t=C[l];return <main>
<header><a className="brand" href={`/${l}`}><img src="/shark-team-logo.png" alt="SHARK TEAM"/><strong>SHARK <i>TEAM</i></strong></a><nav><a href="#about">{t.nav[0]}</a><a href="#basket">{t.nav[1]}</a><a href="#branch">{t.nav[2]}</a><a href="#trial">{t.nav[3]}</a></nav><div className="headActions"><a className="lang" href={l==="ru"?"/uz":"/ru"}>{l==="ru"?"UZ":"RU"}</a><a className="miniCta" href="#trial">{t.cta}</a></div></header>
<section className="hero"><div className="heroGrid"><div className="heroCopy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title.split("\n").map(x=><span key={x}>{x}</span>)}</h1><p className="heroLead">{t.lead}</p><div className="heroActions"><a href="#trial" className="button">{t.cta}<b>↗</b></a><div className="price"><small>{t.trial}</small><strong>{t.price}</strong></div></div></div><div className="heroVisual"><div className="ball">●</div><div className="bigS">S</div><div className="visualLabel"><b>SHARK TEAM</b><span>BASKETBALL / 2026</span></div></div></div></section>
<section id="basket" className="basket"><div className="sectionNo">01 / SPORT</div><div className="basketTitle"><h2>{t.sport}</h2><p>{t.sportText}</p></div><div className="stats"><article><small>{t.ageLabel}</small><strong>{t.age}</strong></article><article><small>{t.daysLabel}</small><strong>{t.days}</strong></article><article><small>{t.timeLabel}</small><strong>{t.time}</strong></article><article><small>{t.coachLabel}</small><strong>{t.coach}</strong></article></div></section>
<section id="about" className="manifest"><p>02 / SHARK TEAM</p><h2>{t.about}</h2><div><span>SHARK</span><p>{t.aboutText}</p></div></section>
<section id="branch" className="branch"><div className="sectionNo">03 / LOCATION</div><div className="branchCard"><div><small>SHARK TEAM</small><h2>{t.branch}</h2><p>{t.school}<br/>{t.place}</p></div><div className="branchRight"><div><small>{t.trial}</small><strong>{t.price}</strong></div><a href="https://yandex.uz/maps/-/CXEXq4iH" target="_blank" rel="noreferrer">{t.route} ↗</a></div></div></section>
<section id="trial" className="trial"><p>04 / {t.trial}</p><div><h2>{t.trial}</h2><p>{t.trialText}</p></div><a href="#trial">{t.cta}<b>→</b></a></section>
<footer><div className="footBrand">SHARK <span>TEAM</span></div><p>{t.footer}</p><p>© 2026 • TASHKENT • RU / UZ</p></footer>
</main>}